### ISSUE TITLE
A "cone-like" error occurred during the calculation

### ISSUE THREAD

**Issue by Alzheimer98** [POVME/POVME3#42]
Hello, I am new to the fields and I am using POVME to calculate the volume of a protein pocket. 
My protein PDB file is extracted from the molecular dynamics simulation results，and in order to facilitate the calculation of the pocket volume of each frame, the trajectory is aligned with the first frame. 
However, when visualizing the final calculation results, there are dozens of frames that appear as they are in the picture.
I think there might be something wrong with my input file . Would you have any clue about this?
I enclose my .ini input file and a screenshot of the "cone-like" error.

[ASN.txt](https://github.com/POVME/POVME/files/7458925/ASN.txt)
![error](https://user-images.githubusercontent.com/77600629/139810389-b427f8ef-77b9-452b-8879-6bf568d5e645.png)

**Comment by j-wags** [comment]
This is an artifact that occurs because of how PDB files are used in this workflow. In VMD, all frames of a PDB file must have an equal number of atoms. However, since the pocket shape will be shown using a different number of dummy atoms each frame (because the pocket gets bigger and smaller), POVME: 

* writes out the maximum number of dummy atoms each frame 
* uses some to fill in the pocket region
* puts the extras at a dummy coordinate (like 99, 99, 99). 

I recommend changing the VMD representation of the pocket from "Lines" to "VDW". Lines is the default, which works well for molecules, but for clouds of dummy atoms it guesses bonds based on the first frame and then draws those bonds for all subsequent frames, leading to the artifact you're seeing.

**Comment by Alzheimer98** [comment]
Thank you so much for your suggestion.
